#!/bin/sh

if [ -e .setup-files ]; then
    while read LINE
        do
            if [ -e ~/$LINE ]; then
                rm ~/$LINE
            fi
            echo "Creating symlink for $LINE..."
            ln -s ~/dotfiles/$LINE ~/$LINE
    done < ".setup-files"
fi

if [ -e .setup-dirs ]; then
    while read LINE
        do
            if [ ! -d ~/$LINE ]; then
                mkdir -p ~/$LINE/
            fi
            echo "Copying $LINE..."
            cp -r ~/dotfiles/$LINE/* ~/$LINE/
    done < ".setup-dirs"
fi

