"NeoBundle Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath^=~/.vim/bundle/neobundle.vim/

" Required:
call neobundle#begin(expand('~/.vim/bundle'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" Add or remove your Bundles here:
NeoBundle 'ctrlpvim/ctrlp.vim'
NeoBundle 'flazz/vim-colorschemes'
NeoBundle 'pearofducks/ansible-vim'
NeoBundle 'Quramy/tsuquyomi'
NeoBundle 'rodjek/vim-puppet'
NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'Shougo/neosnippet-snippets'
NeoBundle 'Shougo/vimproc.vim', {
\ 'build' : {
\     'windows' : 'tools\\update-dll-mingw',
\     'cygwin' : 'make -f make_cygwin.mak',
\     'mac' : 'make -f make_mac.mak',
\     'linux' : 'make',
\     'unix' : 'gmake',
\    },
\ }
NeoBundle 'Shougo/vimshell', { 'rev' : '3787e5' }
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'vim-airline/vim-airline'
NeoBundle 'vim-airline/vim-airline-themes'

" Required:
call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
"End NeoBundle Scripts-------------------------

set showcmd

let &t_Co=256

" terminator for some reason does not send the correct terminal
" version response disabling this for now.
set t_RV=

let g:airline_powerline_fonts = 1
let g:airline_section_c = expand('%:p')
set laststatus=2

syntax enable
colorscheme molokai

command W w !sudo tee % > /dev/null

" This blindly sets tabstop to 8. Disable it
let g:python_recommended_style=0

set autoindent
set tabstop=2
set expandtab
set shiftwidth=2
set softtabstop=2

set number

let g:ctrlp_custom_ignore = {
  \ 'dir': 'node_modules'
  \ }

