#!/bin/bash

sudo apt update && sudo apt install python-dev

mkdir -p /tmp/pip

pushd /tmp/pip
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
popd

rm -rf /tmp/pip

sudo -H pip install -U pip virtualenv setuptools wheel virtualenvwrapper


