#!/bin/bash
mkdir -p /tmp/chrome
pushd /tmp/chrome

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

popd
rm -rf /tmp/chrome 

