#!/bin/zsh

sudo apt install -y perl

sudo wget https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy -O /usr/local/bin/diff-so-fancy

sudo chmod +x /usr/local/bin/diff-so-fancy
