#!/bin/bash

wget https://github.com/sharkdp/bat/releases/download/v0.9.0/bat-musl_0.9.0_amd64.deb
sudo dpkg -i bat-musl_0.9.0_amd64.deb
rm bat-musl_0.9.0_amd64.deb

wget https://github.com/junegunn/fzf-bin/releases/download/0.17.5/fzf-0.17.5-linux_amd64.tgz
tar -xvzf fzf-0.17.5-linux_amd64.tgz
sudo mv ./fzf /usr/local/bin/fzf
rm fzf-0.17.5-linux_amd64.tgz

wget https://github.com/sharkdp/fd/releases/download/v7.2.0/fd-musl_7.2.0_amd64.deb -O fd.deb
sudo dpkg -i fd.deb
rm fd.deb

