#!/bin/bash

sudo echo "deb http://debian.sur5r.net/i3/ $(lsb_release -c -s) universe" | tee -a /etc/apt/sources.list.d/i3.list
sudo apt get update
sudo apt install --allow-unauthenticated install sur5r-keyring
sudo apt update
sudo apt install i3
gsettings set org.gnome.desktop.background show-desktop-icons false
