#!/bin/bash

sudo apt update
sudo apt install -y linux-image-extra-$(uname -r) linux-image-extra-virtual

curl -fsSL https://apt.dockerproject.org/gpg | sudo apt-key add -
apt-key fingerprint 58118E89F3A912897C070ADBF76221572C52609D

echo "deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/docker.list

sudo apt-get update && sudo apt-get install -y docker-engine

sudo groupadd docker
sudo usermod -aG docker $USER
sudo systemctl enable docker
