#!/bin/bash

# Install Virtualbox

echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list

wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -

sudo apt update
sudo apt install virtualbox-5.1 dkms

# Install Vagrant

version="1.9.1"
deb_file="vagrant_${version}_x86_64.deb"

wget https://releases.hashicorp.com/vagrant/$version/$deb_file
